FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# EMIAS
### Send Collected Data Request [POST]

Запрос для отправки собранных данных на сервер.

+ Request (application/json)

        {
            "oms": "1234123412341234",
            "birth_date": 1566899636, //utc
            "data": {
                "steps": [
                { Steps obj}
                ],
                "heart_rate":[
                        { HeartRate obj}
                ],
                "body_temperature":[
                        { BodyTemperature obj}
                ],
                "blood_pressure":[
                        { BloodPressure obj}
                ],
                "blood_glucose":[
                        { BloodGlucose obj}
                ],
                "height": { Height obj},
                "weight":[
                        { Weight obj}
                ],
                "hydration": [
                        { Hydration obj}
                ],
                "activity":[
                        { Activity obj}
                ],
                "sleep": [
                        { Sleep obj}
                ],
                "workout": [
                        { Workout obj }
                ],
                "distance_cycling": [
                        { DistanceCycling obj }
                ],
                "distance_swimming": [
                        { DistanceSwimming obj }
                ],
                "body_mass_index": [
                        { BodyMassIndex obj }
                ]
            }
        }

+ Response 200 (application/json)

    + Body

            {
                "error_code": 0,
                "erroe_message": null,
                "success": true,
            }
            
+ Response 400 (application/json)

    + Body

            {
                "error_code": 12,
                "erroe_message": "Неверный формат поля steps",
                "success": false,
            }
            
## Steps (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional) 
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, require) - Time, unix
+ `value`: `16093` (number, required) - step 
+ `system_version`: `13.1.2` (string, optional) - system version

## HeartRate (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `value_max`: `134` (number, optional) - bpm 
+ `value_min`: `120` (number, optional) - bpm 
+ `value_avg`: `125` (number, required) - bpm 
+ `system_version`: `13.1.2` (string, optional) - system version
+ `condition`: `notSet` (heartRateConditionType, optional) - system version

## BodyTemperature (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `value_max`: `36,8` (number, optional) - celsius 
+ `value_min`: `36,5` (number, optional) - celsius 
+ `value_avg`: `36,6` (number, required) - celsius 
+ `system_version`: `13.1.2` (string, optional) - system version

## BloodPressure (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `blood_pressure_systolic_average`: `110.0` (float, required) - mm hg
+ `blood_pressure_systolic_max`: `110.0` (number, optional) - mm hg
+ `blood_pressure_systolic_min`: `110.0` (number, optional) - mm hg
+ `blood_pressure_diastolic_average`: `70.0` (number, required) - mm hg
+ `blood_pressure_diastolic_max`: `70.0` (number, optional) - mm hg
+ `blood_pressure_diastolic_min`: `70.0` (number, optional) - mm hg
+ `body_position`: `unset` (string, optional)
+ `blood_pressure_measurement_location`: `unset` (string, optional)
+ `system_version`: `13.1.2` (string, optional) - system version

## BloodGlucose (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `value_max`: `16093` (number, optional) - g/mmol
+ `value_min`: `16093` (number, optional) - g/mmol
+ `value_avg`: `16093` (number, required) - g/mmol
+ `relation_to_sleep`: `unset` (string, optional) 
+ `relation_to_meal`: `unset` (string, optional) 
+ `system_version`: `13.1.2` (string, optional) - system version
+ `meal_time`: `after meals` (MealTimeType, optional)

## Height (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `height`: `1,67` (number, required) - meter 
+ `system_version`: `13.1.2` (string, optional) - system version


## Weight (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `value_max`: `45,6` (number, optional) - kg 
+ `value_min`: `46` (number, optional) - kg
+ `value_avg`: `46,1` (number, required) - kg 
+ `system_version`: `13.1.2` (string, optional) - system version

## Hydration (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `volume`: `0,67` (number, required) - liter 
+ `system_version`: `13.1.2` (string, optional) - system version

## Activity (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `activity`: `run` (enum[string], required) - enum 
+ `duration`: `27600000` (number, required) - ms 
+ `num_segments`: `1` (number, required) - unit 
+ `system_version`: `13.1.2` (string, optional) - system version

## Sleep (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `sleep_type`: `inBed` (SleepType, required) - enum 
+ `system_version`: `13.1.2` (string, optional) - system version


## Workout (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `duration`: `1435658272` (number, required) - Time, unix
+ `total_distance`: `1000` (number, optional) - Meter
+ `total_energy_burned`: `200` (number, required) - kkal
+ `workout_type`: `running` (number, required)
+ `system_version`: `13.1.2` (string, optional) - system version

## DistanceCycling (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `value`: `3000` (number, required) - Meter
+ `system_version`: `13.1.2` (string, optional) - system version

## DistanceSwimming (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `value`: `3000` (number, required) - Meter
+ `system_version`: `13.1.2` (string, optional) - system version


## BodyMassIndex (object)
### Properties
+ `source_name`: `Google fit` (string, required) 
+ `device_name`: `Omron cs50` (string, optional)
+ `start_time`: `1435658272` (number, required) - Time, unix
+ `end_time`: `1435658272` (number, required) - Time, unix
+ `value`: `19.7` (number, required)
+ `system_version`: `13.1.2` (string, optional) - system version


        **mealTime**
        + MealTimeType
            + `none`
            + `beforeMeals`
            + `afterMeals`
            
        **sleepType**
        + SleepType
            + `none`
            + `inBed`
            + `asSleep`
            
        **heartRateCondition**
        + heartRateConditionType
            + `active`
            + `notSet`
            + `sedentary`
            
            
        **workoutType**
        + WorkoutType
            + none
            + americanFootball
            + archery
            + australianFootball
            + badminton
            + baseball
            + basketball
            + bowling
            + boxing
            + climbing
            + cricket
            + crossTraining
            + curling
            + cycling
            + dance
            + danceInspiredTraining
            + elliptical
            + equestrianSports
            + fencing
            + fishing
            + functionalStrengthTraining
            + golf
            + gymnastics
            + handball
            + hiking
            + hockey
            + hunting
            + lacrosse
            + martialArts
            + mindAndBody
            + mixedMetabolicCardioTraining
            + paddleSports
            + play
            + preparationAndRecovery
            + racquetball
            + rowing
            + rugby
            + running
            + sailing
            + skatingSports
            + snowSports
            + soccer
            + softball
            + squash
            + stairClimbing
            + surfingSports
            + swimming
            + tableTennis
            + tennis
            + trackAndField
            + traditionalStrengthTraining
            + volleyball
            + walking
            + waterFitness
            + waterPolo
            + waterSports
            + wrestling
            + yoga
            + barre
            + coreTraining
            + crossCountrySkiing
            + downhillSkiing
            + flexibility
            + highIntensityIntervalTraining
            + jumpRope
            + kickboxing
            + pilates
            + snowboarding
            + stairs
            + stepTraining
            + wheelchairWalkPace
            + wheelchairRunPace
            + taiChi
            + mixedCardio
            + handCycling
            + discSports
            + fitnessGaming
            + other